definitions:
  models.Candidate:
    properties:
      address:
        items:
          type: Address
        type: array
      age:
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: string
      mobile:
        type: string
      name:
        type: string
      roll_number:
        type: string
      updatedAt:
        type: string
    required:
    - address
    - email
    - id
    - mobile
    - name
    - roll_number
    type: object
  models.HeartbeatResponse:
    properties:
      data:
        type: Heartbeat
      error:
        type: APIError
    type: object
  models.Response:
    properties:
      data:
        type: object
      error:
        type: APIError
    type: object
info:
  contact: {}
  license: {}
paths:
  /admin/_health:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HeartbeatResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Get Health
      tags:
      - Admin
  /admin/_info:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HeartbeatResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Get Info
      tags:
      - Admin
  /admin/heartbeat:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HeartbeatResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Get Heartbeat
      tags:
      - Admin
  /admin/heartbeat/_start:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HeartbeatResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Enable Heartbeat
      tags:
      - Admin
  /admin/heartbeat/_stop:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HeartbeatResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Disable Heartbeat
      tags:
      - Admin
  /candidates:
    get:
      parameters:
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: List Candidate
      tags:
      - Candidate
    post:
      parameters:
      - description: Create Candidate
        in: body
        name: candidate
        required: true
        schema:
          $ref: '#/definitions/models.Candidate'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Create Candidate
      tags:
      - Candidate
  /candidates/{CandidateID}:
    delete:
      parameters:
      - description: Candidate ID
        in: path
        name: CandidateID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Delete Candidate
      tags:
      - Candidate
    get:
      parameters:
      - description: Candidate ID
        in: path
        name: CandidateID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Get Candidate
      tags:
      - Candidate
    put:
      parameters:
      - description: Update Candidate
        in: body
        name: candidate
        required: true
        schema:
          $ref: '#/definitions/models.Candidate'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
            type: object
      summary: Update Candidate
      tags:
      - Candidate
